name: 'Istioctl installer'
description: 'Install a specific version of istioctl binary. Acceptable values are latest or any semantic version string like 1.9.7'
author: 'Carl Nygard'

inputs:
  version:
    description: 'Version of istioctl'
    required: true
    default: '1.15.3'

outputs:
  istioctl-path:
    description: 'Path to the cached istioctl binary'

runs:
  using: 'node16'
  main: 'src/main.ts'

branding:
  color: 'blue'
