name: Actions snapshot
on:
  push:
    branches:
      - main
    tags-ignore:
      - release-**
      - v**

jobs:
  istioctl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build
      uses: npm run build
    - name: Test
      run: npm run test
