name: Tag GitHub Action
on:
  push:
    tags:
      - release-**
      - v**

jobs:
  istioctl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: 'https://npm.pkg.github.com'
    - name: Install npm dependencies
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build
      run: npm rebuild && npm run prepare --if-present
    - name: Test
      run: npm run test
    - name: Setup Istioctl
      uses: ./
    - name: Check Istioctl
      run: |
        istioctl version --remote=false
    - name: Publish action
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
